source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

install! 'cocoapods', :deterministic_uuids => false

target 'HelloGDApi' do
  # Depend on the generated GDApiLibrary library.
  pod 'GDApiLibrary', :path => '.'
end
